### ISSUE TITLE
React from a CDN

### ISSUE THREAD

**Issue by guilhermebruzzi** [nitin42/react-perf-devtool#10]
Hi im trying to use with React from a CDN: https://unpkg.com/react-dom@16.2.0/umd/react-dom.development.js

Is it possible, or only if React is on the bundle with the commentary on react-dom you said on the README?

**Comment by nitin42** [comment]
Hi there!

Seems like, commenting the line in react-dom bundle is the only way you can let this tool to intercept the measures.

If I have any update on this, I'll let you know or I'll directly make the changes to README.md.

**Comment by nitin42** [comment]
Also, you have to edit the common js bundle file!

**Comment by guilhermebruzzi** [comment]
@nitin42 thanks, I will try to include React on the bundle when on development mode, and switch to  CDN only in production, to try your tool! :)

**Comment by nitin42** [comment]
Something cool in the pipeline. Hopefully, it will resolve this issue!

**Comment by nitin42** [comment]
After this new update, no more commenting the line in react-dom bundle.

**Comment by guilhermebruzzi** [comment]
Nice! :)

**Comment by nitin42** [comment]
Released a new update! Should work with the cdn!

**Comment by nitin42** [comment]
Check out the new docs before using the devtool!
