### ISSUE TITLE
Insights/Filters

### ISSUE THREAD

**Issue by siddharthkp** [nitin42/react-perf-devtool#14]
First of all, this is really cool! I'm going to dig up the source to learn some stuff.

After using this on the app I'm working on right now, I have feelings 😅

I don't mean to pick on your work, just trying to give constructive feedback because you asked for it.

&nbsp;

The blanket issue that I see is:

I have the results but I don't know what to do with it. Data without insights is just numbers.

&nbsp;

Examples:

1. Some components take more time than others, that's expected, how much time is too much time though?

	I see `BrowserRouter`  from `react-router` is at the top of the list with `76.14ms` to mount, is that bad? Should I do something?

2. `componentWillMount` should be fast, right? Can I filter/sort out components that have really long times to see if something needs my attention.

&nbsp;

Suggestions:

Taking inspiration from @FormidableLabs's [electron-webpack-dashboard](http://formidable.com/blog/2017/introducing-electron-webpack-dashboard)
- present data in a way that is easy to derive conclusions from 
- make users feel like they work at NASA

Here's my attempt at it:

![react-perf](https://user-images.githubusercontent.com/1863771/34383092-0b6b12fa-eb39-11e7-8029-efbc5f46e608.jpg)

1. Show most important metrics on top
2. Show components that need attention (this is very opinionated, might send people the wrong way in some cases, @bvaughn might be able to suggest a smarter way)
3. Highlight problem areas from the list of components
4. Let people sort the table based on columns (example: sort by update time)

**Comment by nitin42** [comment]
Hey!

Thanks for such a constructive feedback and suggested solution. The design looks really great but I wish I had some more time ( very busy this coming month ).

I agree with you that its needs to be more comprehensive but I already have mentioned in the docs about the stats (how they are calculated and what they mean, in detail) generated by the devtool and I guess this should make it a little easy to understand the stats.

Meanwhile, I am going to explore your idea and will compare the trade-offs. 

Thanks 😄

**Comment by nitin42** [comment]
The new release makes the extension more intuitive, taking inspiration from your design. Closing this !
