### ISSUE TITLE
Pending Events is not decreasing & statistics not being updated

### ISSUE THREAD

**Issue by pushqin** [nitin42/react-perf-devtool#22]
Hi,

At the initial render i get the statistics.
Then i click a button that re-render some elements, pending events receiving some value,then this number and statistic is stuck.
When i click my button again, the number is lowered(with each click i delete an element) but the statistics is still not updated.

This is my packages

    "babel": "^6.23.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.4"

Any ideas?

![image](https://user-images.githubusercontent.com/1239488/35642371-987b5e0e-06cb-11e8-9ccc-bc3ad811c127.png)

**Comment by evertonaleixo** [comment]
Did you have checked if you are using setState method?

**Comment by pushqin** [comment]
Of course,the click chages the state , removes one item from array. I aslo tried changing the state on emty application, pending events were 6 but statistic not updated.

**Comment by nitin42** [comment]
Hm.. strange! I am not facing this issue when tested locally on a project of mine. On every re-render, I get the new statistics. Reinstall the extension and then check to see if it displays the new stats on a re-render ?

Let me know!

**Comment by nitin42** [comment]
Well, Brenda recently talked about this tool at **ReactNYC Meetup** and if you watch her talk, then you will see that the stats and pending events are updated on a new render. No issues!

Closing this 😄

**Comment by seanparsons** [comment]
@nitin42 I _think_ I'm seeing this issue on my project, a bunch of renders are being triggered but the results don't change at all.

**Comment by nitin42** [comment]
I'll look into this issue again next week 😄
