### ISSUE TITLE
Getting started with react-perf-devtool and create-react-app

### ISSUE THREAD

**Issue by JamieMason** [nitin42/react-perf-devtool#39]
Hi @nitin42,
Thanks for this great Extension, however I have been having some trouble getting it to work and was hoping you could point out where I'm going wrong.

I have created a test case below so others can reproduce it, I am probably missing something obvious.

## Steps to reproduce

1. ```bash
   npm install -g create-react-app
   ```
1. ```bash
   create-react-app reduced-test-case
   ```
1. ```bash
   cd reduced-test-case
   ```
1. ```bash
   yarn add -D react-perf-devtool
   ```
1. ```bash
   echo "
   const { registerObserver } = require('react-perf-devtool');
   registerObserver();
   " >> ./src/index.js
   ```
1. ```bash
   yarn start
   ```
1. Visit http://localhost:3000/?react_perf
1. Open **React Performance Devtools** Tab
1. Try refreshing the page, hitting reload button, reopening devtools etc.

## Expected Behaviour

**React Performance Devtools** Tab shows performance data about the React app.

## Actual Behaviour

**React Performance Devtools** shows:

> An error occurred while collecting the measures. This is possibly due to
> absence of register observer hook in your project. See the detailed documentation on how to register a top level observer in your React application.
> 
> your project is not using React.
> If above solutions don't work, then try reloading the plugin or close and reopen the inspected window.

**Comment by nitin42** [comment]
Hey! 

I tested the tool and package with `create-react-app`, and everything seems to be working fine. Check out this gif -

![gif](http://g.recordit.co/M0Pjh48zhC.gif)


Make sure the chrome extension you have installed is the latest (Version: 5.1) and also the npm module (latest is ^3.0.7).

```
yarn add react-perf-devtool@3.0.7
```

**Comment by nitin42** [comment]
Oops! I got you. After Step 5. your `src/index.js` ended up with -

```jsimport React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();

const { registerObserver } = require('react-perf-devtool');
registerObserver();
```

Here, `registerObserver()` is not hoisted so it is not able infer which React components are present.

I made some changes.

```js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

const { registerObserver } = require('react-perf-devtool');
registerObserver();

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

and got it working!

Hope it helps. Let me know 😃

**Comment by JamieMason** [comment]
Thanks @nitin42 I'll give this a try. So I understand, is the requirement that `registerObserver()` must be called before `ReactDOM.render` is called? That something needs to be present before the rendering is performed?

**Comment by nitin42** [comment]
Yes! I should have added this to the docs. Anyway, thanks for reporting this!

**Comment by nitin42** [comment]
Closing this! Open to feedback though.

**Comment by JamieMason** [comment]
No problem @nitin42. That change didn't seem to work for me but I will try when I get some time to revisit it. _maybe_ I have another Chrome Extension that conflicts with this one I don't know.

**Comment by nitin42** [comment]
Yup, may be. Let me know. Happy to help!

**Comment by Fralleee** [comment]
Why close the issue when it clearly wasn't resolved? :(
