### ISSUE TITLE
Support for older versions of React

### ISSUE THREAD

**Issue by kszeluk** [nitin42/react-perf-devtool#4]
Are there any plans when this cool devtool will support older versions of React?

**Comment by nitin42** [comment]
Yes. I've plans for adding the support for older versions of React! I'll update the extension soon.

Stay tuned!

**Comment by nitin42** [comment]
Hello! So there are some changes in my roadmap. I have decided to drop support for older version of React because for those versions, you can already find the tools that are perfectly compatible.
