### ISSUE TITLE
React is not loading performance measurements when using nodejs and react with stores

### ISSUE THREAD

**Issue by srinivas640** [nitin42/react-perf-devtool#41]
Not capturing measurements with the following code.

const {registerObserver} = require('react-perf-devtool')
const store = createStore();
store.dispatch(getChannel());
store.dispatch(getChannelList());
unregister();
const options = {
  shouldLog: true,
  port: 9081
  // Assuming you've these components in your project
}
function callback(measures) {
  // do something with measures
  alert("measures" + measures);
}

registerObserver(options, callback);
ReactDOM.render(
    <Provider store={store} >
        <App />
    </Provider>, document.getElementById('root')
);

**Comment by nitin42** [comment]
Closing this! Related #36
