### ISSUE TITLE
Updating stats in the extension view

### ISSUE THREAD

**Issue by svk31** [nitin42/react-perf-devtool#42]
Are the stats supposed to be updated as you navigate around the app?

I only get stats for the initial (partial) load of my app then nothing happens afterwards, the pending events count changes as I move around, but nothing else happens.

**Comment by nitin42** [comment]
Have you tried clicking on the reload button in the extension ?

**Comment by nitin42** [comment]
Closing since this issue will require an architecture change. Feel free to open a PR and we can continue the discussion there!
