### ISSUE TITLE
Extension not working in SSR 

### ISSUE THREAD

**Issue by gruler05** [nitin42/react-perf-devtool#50]
I was trying to make the extension work for SSR also saw the other issue #8. Wondering why it won't work on the Server Side Rendering? Isn't this the object `__REACT_PERF_DEVTOOL_GLOBAL_STORE__` which you need to render the extension? Also when i log out the measures it logs out all the info about the components correctly. It works out of the blue sometimes and when i try to run it again, it gives me the error message again.

**Comment by nitin42** [comment]
Hmm... that's strange. I'll look into this issue sometime later next week!

**Comment by nitin42** [comment]
Hey, try this new beta release of observer hook

```js
yarn add react-perf-devtool@3.1.8-beta.2
```

then configure a timeout value like this

```js
registerObserver({ timeout: 4000 // or some other value })
```

Timeout value defers the initialisation process of the extension. It makes sure that the extension will load only after the app has loaded successfully!

**Comment by gruler05** [comment]
cool, I will check. Thanks !

**Comment by nitin42** [comment]
Released [a new version](https://github.com/nitin42/react-perf-devtool/releases/tag/3.1.8) that may be useful.

Closing this issue since I don't know how we can make this tool work with SSR.
