### ISSUE TITLE
Configurable timeout for initializing the extension?

### ISSUE THREAD

**Issue by jrnail23** [nitin42/react-perf-devtool#51]
Hi, I'm trying to get the chrome extension working, but it keeps telling me this:
```
An error occurred while collecting the measures. This is possibly due to
absence of register observer hook in your project. See the detailed documentation on how to register a top level observer in your React application.

your project is not using React.
If above solutions don't work, then try reloading the plugin or close and reopen the inspected window.
``` 
I have installed the observer hook, and I definitely am using React, but my app does take a ridiculously long time to load (one of the reasons we need a good react profiler so badly!), so I suspect your extension's initialization may be timing out before my app is loaded.  If that is the case, perhaps you could make that timeout configurable?

**Comment by nitin42** [comment]
Oops! Sorry for that. I am going to work on the next release that will hopefully fix this issue.

**Comment by nitin42** [comment]
Found the bug! I'll release a new version of observer and tool soon. Thanks!

**Comment by nitin42** [comment]
Heya, I've released a new version of the observer hook.

Install the new beta with

```
yarn add react-perf-devtool@3.1.8-beta.2
```

Configure the timeout value like this -

```js
registerObserver({ timeout: desire_value_in_number })
```

Let me know if it works and then I'll go ahead and update the docs.

**Comment by jrnail23** [comment]
Wow @nitin42, that was ridiculously fast.  I'll give it a shot!

**Comment by nitin42** [comment]
Did you got it working with the new beta release ?

**Comment by jrnail23** [comment]
finally about to try it, @nitin42.  I'll let you know ASAP

**Comment by nitin42** [comment]
Awesome!

**Comment by nitin42** [comment]
Hm... Strange! Can you show me a screenshot where you are using the observer hook ?

**Comment by nitin42** [comment]
Also, if it gives the error after two sec. then I am sure you must be using react-perf-devtool@3.0.8 and not @3.1.8-beta.2!

**Comment by nitin42** [comment]
It's perfectly working... see this video where I am using the current beta on my machine. I am adjusting the timeout value that directly impacts the initialisation process - [video source](https://www.dropbox.com/s/d8mgjimoi160ss0/Screen%20Recording%202018-08-31%20at%201.04.03%20AM.mov?dl=0
)

Please make sure that you've `react-perf-devtool@3.1.8-beta.2` installed!

**Comment by jrnail23** [comment]
I'll doublecheck and get back to you ASAP

**Comment by nitin42** [comment]
Strange! Are you doing server side rendering or using any server side React framework ?

**Comment by nitin42** [comment]
I've released a stable version `registerObserver` hook i.e `react-perf-devtool@3.1.8`

I've thoroughly tested the build on three of my websites and apps built with React and I can confirm that everything is working fine.

**Comment by jrnail23** [comment]
@nitin42, we're definitely not doing any server-side rendering.  Perhaps we're doing something else that the tool doesn't like.  What are the general assumptions that the tool expects?

**Comment by agandra** [comment]
@nitin42 I am having the same issue as @jrnail23 .  Sometimes the devtools waits the full timeout length before showing me the performance statistics.  Othertimes, it does not wait the timeout length and just shows the error message.  It appears to work inconsistently.

I am not doing server side rendering or using any server side React framework.
