### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by jasonLaster** [nitin42/react-perf-devtool#7]
👋 From the Firefox Devtools team!

Great work! We use React + Redux to build the Firefox DevTools and are thrilled you're looking at helping measure performance :)

It looks like you have Firefox support on your roadmap. Feel free to ask me, @rpl, or @captainbrosset any questions :)

We're also in [slack](https://devtools-html-slack.herokuapp.com/) if you wanna give us a holler

**Comment by nitin42** [comment]
Awesome! Thank you. I'll start working on the Firefox extension in the coming days and will let you know of any doubts.

**Comment by nitin42** [comment]
Well, I've ported the extension successfully to Firefox (needs some polishing though). So, closing this now!

Add-on link - https://addons.mozilla.org/en-US/firefox/addon/nitin-tulswani/

Happy holidays!!

**Comment by jasonLaster** [comment]
What polish does it need?

**Comment by nitin42** [comment]
Styling and other cosmetic stuff!

**Comment by jasonLaster** [comment]
cool - perhaps file some small issues and i can take a look later :)

**Comment by nitin42** [comment]
That's so awesome of you! I'll let you know.
