### ISSUE TITLE
Support Server Side Rendered applications

### ISSUE THREAD

**Issue by damusnet** [nitin42/react-perf-devtool#8]
I tried using this tool to profile a React application built with Next.js, and unless I'm missing something, it doesn't measure anything in a server-side rendered page.

I see 2 ways that this extension could be useful for an SSR app:

1. measure what happens during rehydration
1. measure arbitrarily during time A and B, on a click action for instance, so that we can analyze during a page change, instead of having to do a reload

I have no idea if any of those things are practical or even possible.

**Comment by nitin42** [comment]
Hey! Ya we should definitely support SSR. I'll let you know when I have something. Thanks!

**Comment by nitin42** [comment]
Hmm.. seems like right now there is no feasible way to measure the performance on SSR. But, the React may come up with an API for measuring the performance which may help with SSR.

If you find anything useful on this, let me know!

**Comment by damusnet** [comment]
Hi, thanks for looking into it.
Too bad it isn't possible for now.
