### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by jasonLaster** [nitin42/react-perf-devtool#9]
The CONTRIBUTING guide is a great start. Can you provide some information about what to do `post-yarn install`

1. how to start the build step
2. how to install the firefox addon or chrome extension
3. how to inspect / debug the extension

perhaps some links to the general architecture (content script, background page, panel)...

**Comment by nitin42** [comment]
Working on it!

**Comment by nitin42** [comment]
Added instructions to [CONTRIBUTING.md](https://github.com/nitin42/react-perf-devtool/blob/master/CONTRIBUTING.md).

Closing this!

**Comment by nitin42** [comment]
Let me know if you need some more help.
